### ISSUE TITLE
java.lang.IllegalArgumentException: invalid comparison: java.lang.String and com.wjy.mapper2sql.parse.param.SimpleSqlParamMap

### ISSUE THREAD

**Issue by 970263611** [handsomestWei/mybatis-mapper2sql#1]
1.0.1版本
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE mapper
        PUBLIC "-//mybatis.org//DTD Mapper 3.0//EN"
        "http://mybatis.org/dtd/mybatis-3-mapper.dtd">
<mapper namespace="com.psbc.monitor.dao.jj.JjCancelOrderDao">
  <insert id="save" parameterType="com.psbc.monitor.jj.module.CancelOrderMessage">
    insert into "JJ_CANCEL_ORDER_TABLE"
    <trim prefix="(" suffix=")" suffixOverrides=",">
      <if test="oldAppFormNo != null and '' != oldAppFormNo">
        "OLD_APP_FORM_NO",
      </if>
      <if test="itbkFundPaymModeFlag != null and '' != itbkFundPaymModeFlag">
        "ITBK_FUND_PAYM_MODE_FLAG",
      </if>
      <if test="txDate != null">
        "TX_DATE",
      </if>
      <if test="lastModStamp != null">
        "LAST_MOD_STAMP",
      </if>
      <if test="crspFundCorpBusiNo != null and '' != crspFundCorpBusiNo">
        "CRSP_FUND_CORP_BUSI_NO",
      </if>
      <if test="cfmFlag != null and '' != cfmFlag">
        "CFM_FLAG",
      </if>
      <if test="inOutFlagCd != null and '' != inOutFlagCd">
        "IN_OUT_FLAG_CD",
      </if>
      <if test="txTime != null and '' != txTime">
        "TX_TIME",
      </if>
      <if test="cancelStatus != null and '' != cancelStatus">
        "CANCEL_STATUS",
      </if>
      <if test="sendFundCorpAgrNo != null and '' != sendFundCorpAgrNo">
        "SEND_FUND_CORP_AGR_NO",
      </if>
      <if test="busiTypeCode != null and '' != busiTypeCode">
        "BUSI_TYPE_CODE",
      </if>
      <if test="scenarioType != null">
        "SCENARIO_TYPE",
      </if>
    </trim>
   <trim prefix="values (" suffix=")" suffixOverrides=",">
      <if test="oldAppFormNo != null and '' != oldAppFormNo">
        #{oldAppFormNo},
      </if>
      <if test="itbkFundPaymModeFlag != null and '' != itbkFundPaymModeFlag">
        #{itbkFundPaymModeFlag},
      </if>
      <if test="txDate != null">
        #{txDate},
      </if>
      <if test="lastModStamp != null">
        #{lastModStamp},
      </if>
      <if test="crspFundCorpBusiNo != null and '' != crspFundCorpBusiNo">
        #{crspFundCorpBusiNo},
      </if>
      <if test="cfmFlag != null and '' != cfmFlag">
        #{cfmFlag},
      </if>
      <if test="inOutFlagCd != null and '' != inOutFlagCd">
        #{inOutFlagCd},
      </if>
      <if test="txTime != null and '' != txTime">
        #{txTime},
      </if>
      <if test="cancelStatus != null and '' != cancelStatus">
        #{cancelStatus},
      </if>
      <if test="sendFundCorpAgrNo != null and '' != sendFundCorpAgrNo">
        #{sendFundCorpAgrNo},
      </if>
      <if test="busiTypeCode != null and '' != busiTypeCode">
        #{busiTypeCode},
      </if>
      <if test="scenarioType != null">
        #{scenarioType},
      </if>
    </trim>
  </insert>
</mapper>

**Comment by 970263611** [comment]
[JjCancelOrderMapper.txt](https://github.com/user-attachments/files/18120241/JjCancelOrderMapper.txt)
txt文件改成xml即可，就可以复现上面的错误

**Comment by handsomestWei** [comment]
需要您在xml文件添加resultMap标签，并定义字段名称和jdbcType类型。mock依据类型才能推断，不能无中生有^-^。例如：
```
<resultMap type="com.xxx" id="xxxResult">
    <result property="createTime" column="create_time" jdbcType="TIMESTAMP"/>
</resultMap>
```
可以使用其他插件生成resultMap，完善后您再尝试一下

**Comment by handsomestWei** [comment]
这个[commit](https://github.com/handsomestWei/mybatis-mapper2sql/commit/f725d41b9eeda79b3e5c391f3330ec8c7c1d9781)应该修复了，您再试一下

**Comment by 970263611** [comment]
收到感谢，我们场景还挺复杂的，后面有问题可能还需要多多交流。

**Comment by 970263611** [comment]
<select id="selectComeAndPay" resultType="com.psbc.monitor.jj.module.ComeAndPayMessage">
        select *
        from "JJ_COME_AND_PAY_TABLE"
        <if test="sendFundCorpAgrNo != null and '' != sendFundCorpAgrNo">
            where "SEND_FUND_CORP_AGR_NO" = #{sendFundCorpAgrNo}
        </if>
        <if test="txAccNo != null and '' != txAccNo">
            where "PAYER_ACCNO" = #{txAccNo} and "ACCOUNTING_DATE" = #{txDate}
        </if>
    </select>

**Comment by 970263611** [comment]
> select * from "JJ_COME_AND_PAY_TABLE" where "SEND_FUND_CORP_AGR_NO" = #{sendFundCorpAgrNo} where "PAYER_ACCNO" = #{txAccNo} and "ACCOUNTING_DATE" = #{txDate}

像这样的sql也无法解析，我看是德鲁伊格式化的时候发现两个where，应该是动态sql解析时候的问题，好像是无解的

**Comment by 970263611** [comment]
[测试文件.txt](https://github.com/user-attachments/files/18138654/default.txt)
可以用这个文件ce's测试

> > select * from "JJ_COME_AND_PAY_TABLE" where "SEND_FUND_CORP_AGR_NO" = #{sendFundCorpAgrNo} where "PAYER_ACCNO" = #{txAccNo} and "ACCOUNTING_DATE" = #{txDate}
> 
> 像这样的sql也无法解析，我看是德鲁伊格式化的时候发现两个where，应该是动态sql解析时候的问题，好像是无解的

可以用这个文件测试
[测试文件.txt](https://github.com/user-attachments/files/18138656/default.txt)

**Comment by 970263611** [comment]
还有我发现mock功能失效了

**Comment by 970263611** [comment]
我看了下代码是校验的resultMap，没考虑resultType的场景

**Comment by handsomestWei** [comment]
mock功能需要在mapper  xml中提供resultMap标签，定义字段名称和jdbcType类型，才能做推断。这个可以用其他插件根据表结构自动生成一下

**Comment by handsomestWei** [comment]
关于你上面提到的[双where](https://github.com/handsomestWei/mybatis-mapper2sql/issues/1#issuecomment-2543421479)
是工具注入if标签后默认test结果均为true，所有的条件sql都会被拼接。以`select id="selectComeAndPay"`为例，标签里的明文含有where且出现多次。这种写法目前不太好适配。

**Comment by handsomestWei** [comment]
关于[resultMap缺省](https://github.com/handsomestWei/mybatis-mapper2sql/issues/1#issuecomment-2543435752)的场景，[新版](https://github.com/handsomestWei/mybatis-mapper2sql/commit/0f87e8724534807dbd1dd81e8aa1a6504f84e851)增加了运行时从表结构动态获取表字段名称和类型，可以试一下 @970263611
